[package]
name = "send_file_to_azure"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
hmac = "0.12.1"
reqwest = "0.12.5"
sha2 = "0.10.8"
tokio = { version = "1.38.0", features = ["full"] }
xml = "0.8.20"


